name:                   haskell-sandbox
version:                '0.1.0.0'
description:            Sandbox for investigating Haskell
author:                 Martin Rist
maintainer:             mlr-github@martinrist.com
copyright:              2018 Martin Rist
license:                BSD3
github:                 martinrist/haskell-sandbox

library:
  source-dirs: src
  dependencies:
    - base
    - time
    - hspec
    - containers
    - QuickCheck
    - optparse-applicative
    - checkers
    - bytestring
    - wreq
    - random
    - transformers
    - trifecta
    - parsers
    - text
    - raw-strings-qq
    - attoparsec
    - scotty
    - criterion
    - bytestring
    - network
    - sqlite-simple
    - safe
    - wai
    - warp
    - aeson
    - servant
    - servant-server
    - servant-client
    - servant-docs

executables:
  optparse-applicative-exe:
    main:           Main.hs
    source-dirs:    app/optparse-applicative
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - optparse-applicative

  interact-with-exe:
    main:           InteractWith.hs
    source-dirs:    app/realWorldHaskell/interact-with
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base

  hangman:
    main:           Main.hs
    source-dirs:    app/programmingHaskell/hangman
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-sandbox

  encrypt:
    main:           Main.hs
    source-dirs:    app/programmingHaskell/encrypt
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-sandbox
      - optparse-applicative

  morse:
    main:           Main.hs
    source-dirs:    app/programmingHaskell/morse
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wno-type-defaults
    dependencies:
      - base
      - haskell-sandbox

tests:
  haskell-sandbox-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - hspec
      - hspec-discover
      - haskell-sandbox
      - QuickCheck
      - checkers
      - hspec-checkers
